"""Deterministic MVP planner for mascot story explainer Reels."""

from __future__ import annotations

from app.content.mascot_story_schemas import MascotStoryPlan, MascotStoryScene
from app.mascot.mascot_profile import MascotProfile


def plan_mascot_story_reel(topic: str, niche: str, mascot: MascotProfile) -> MascotStoryPlan:
    normalized = " ".join(topic.strip().split()) or "What is the relationship between oil prices and the dollar?"
    if "oil" in normalized.lower() and "dollar" in normalized.lower():
        return _oil_dollar_plan(normalized, niche, mascot)
    return _generic_plan(normalized, niche, mascot)


def _oil_dollar_plan(topic: str, niche: str, mascot: MascotProfile) -> MascotStoryPlan:
    return MascotStoryPlan(
        topic=topic,
        niche=niche or "economy",
        title="Oil and the Dollar",
        story_angle="Miko explains the oil-dollar relationship with a wallet story, a dollar meter, and a clear caveat.",
        audience="Curious viewers who want a useful economy answer in under 35 seconds.",
        core_question="What is the relationship between oil prices and the dollar?",
        simple_answer="Oil is often traded in dollars, so price moves can change import bills, dollar demand, inflation pressure, and currency stress.",
        analogy="Think of an importer as a small wallet that must find more dollars when each barrel costs more.",
        caveat="The link is indirect and context-dependent. Oil importers and exporters can feel opposite effects, and rates, inflation, trade balances, and risk sentiment matter too. This is not financial advice.",
        caption=(
            "Oil and the dollar are connected, but not by a simple one-way rule. Many oil trades are priced in US dollars, "
            "so importers may need more dollars when oil rises. That can affect import bills, inflation pressure, trade balances, "
            "and local currencies. Exporters can feel it differently because higher oil may bring more dollar revenue. Context matters. "
            "This is educational content, not financial advice."
        ),
        hashtags=["economy", "oilprices", "usdollar", "explained", "learnfinance"],
        mascot_id=mascot.mascot_id,
        scenes=[
            MascotStoryScene(
                scene_number=1,
                role="hook",
                duration_target=2.8,
                visual_type="mascot_ai",
                visual_goal="Miko holding a shiny oil drop in one tiny hand and a dollar coin in the other, surprised but confident.",
                mascot_action="holding an oil drop and a dollar coin while looking at the viewer",
                setting="warm miniature desk with simple economy props",
                media_query="oil drop dollar coin economy explainer mascot",
                voiceover_line="Oil moves. Money reacts.",
                on_screen_caption="OIL MOVES",
                key_words=["oil", "money", "reacts"],
                required_visual_elements=["Miko", "oil drop", "dollar coin"],
                forbidden_visual_elements=["human presenter", "text", "logo"],
                fact_claim="Oil and currencies can be linked through global trade.",
                source_needed=True,
                emotion="surprised",
            ),
            MascotStoryScene(
                scene_number=2,
                role="question",
                duration_target=3.1,
                visual_type="mixed",
                visual_goal="Miko points at a simple world map with oil barrels moving across oceans toward a dollar symbol.",
                mascot_action="pointing at a simple world map",
                setting="miniature global trade table",
                media_query="oil tanker global trade dollar",
                voiceover_line="Why would oil push a currency?",
                on_screen_caption="THE QUESTION",
                key_words=["barrel", "currency"],
                required_visual_elements=["Miko", "map", "oil barrels", "dollar symbol"],
                forbidden_visual_elements=["role label", "text-heavy chart"],
                fact_claim="Oil trade can influence currency pressure.",
                source_needed=True,
                emotion="curious",
            ),
            MascotStoryScene(
                scene_number=3,
                role="analogy",
                duration_target=3.4,
                visual_type="object_scene_ai",
                visual_goal="A tiny importer wallet tries to buy an oil barrel; the price tag rises and the wallet gets squeezed.",
                mascot_action="watching a tiny wallet get squeezed by a rising oil price",
                setting="playful tabletop analogy scene",
                media_query="wallet oil barrel price rising analogy",
                voiceover_line="An importer wallet needs more dollars when fuel gets pricier.",
                on_screen_caption="THE WALLET",
                key_words=["wallet", "dollars", "fuel"],
                required_visual_elements=["wallet", "oil barrel", "rising price arrow"],
                forbidden_visual_elements=["financial advice", "trading signal"],
                fact_claim="Higher oil prices can raise import bills for importers.",
                source_needed=True,
                emotion="concerned",
            ),
            MascotStoryScene(
                scene_number=4,
                role="mechanism",
                duration_target=4.0,
                visual_type="chart_motion",
                visual_goal="Reel-native motion infographic: oil price rises, importer wallet squeezes, dollar demand meter rises, caution appears.",
                mascot_action="holding the oil drop beside an animated dollar demand meter",
                setting="clean motion infographic space",
                media_query="oil price import bill dollar demand currency pressure infographic",
                voiceover_line="More dollar demand can pressure local money.",
                on_screen_caption="THE LINK",
                key_words=["dollar", "demand", "pressure"],
                required_visual_elements=["oil price arrow", "wallet", "dollar demand meter", "caution"],
                forbidden_visual_elements=["PowerPoint chart", "tiny title", "raw prompt text"],
                fact_claim="Higher oil prices can increase dollar demand and currency pressure for importers.",
                source_needed=True,
                emotion="explaining",
            ),
            MascotStoryScene(
                scene_number=5,
                role="example",
                duration_target=3.5,
                visual_type="broll_photo",
                visual_goal="Fuel station, refinery, tanker ship, or oil barrels with a strong vertical crop and useful real-world context.",
                mascot_action="small corner reaction only if mixed media is used",
                setting="real-world energy scene",
                media_query="oil refinery fuel station tanker ship oil barrels",
                voiceover_line="Importers may face bigger bills and inflation pressure.",
                on_screen_caption="IMPORTERS FEEL IT",
                key_words=["importer", "bill", "inflation"],
                required_visual_elements=["oil or fuel context", "clear subject"],
                forbidden_visual_elements=["low resolution", "text-heavy image"],
                fact_claim="Oil importers can face higher bills and inflation pressure when oil prices rise.",
                source_needed=True,
                emotion="concerned",
            ),
            MascotStoryScene(
                scene_number=6,
                role="example",
                duration_target=3.4,
                visual_type="broll_photo",
                visual_goal="Tanker ship or export terminal scene showing the exporter side of the same story.",
                mascot_action="none",
                setting="real-world export scene",
                media_query="oil tanker export terminal crude oil shipping",
                voiceover_line="Exporters may earn more dollars, so effects differ.",
                on_screen_caption="EXPORTERS DIFFER",
                key_words=["exporter", "revenue", "differently"],
                required_visual_elements=["tanker or export terminal", "energy trade context"],
                forbidden_visual_elements=["trading recommendation", "human host"],
                fact_claim="Oil exporters may receive more dollar revenue when oil prices rise.",
                source_needed=True,
                emotion="thinking",
            ),
            MascotStoryScene(
                scene_number=7,
                role="twist",
                duration_target=3.4,
                visual_type="mixed",
                visual_goal="Miko raises a caution sign beside floating icons for inflation, interest rates, trade balance, and risk sentiment.",
                mascot_action="raising a small caution sign while looking thoughtful",
                setting="clean educational icon scene",
                media_query="inflation interest rates trade balance risk sentiment icons",
                voiceover_line="The trap: rates, trade balances, and fear matter too.",
                on_screen_caption="THE TRAP",
                key_words=["not", "automatic", "matter"],
                required_visual_elements=["Miko", "caution symbol", "four simple icons"],
                forbidden_visual_elements=["financial advice", "crowded text"],
                fact_claim="Currency effects depend on broader macroeconomic context.",
                source_needed=True,
                emotion="thinking",
            ),
            MascotStoryScene(
                scene_number=8,
                role="takeaway",
                duration_target=3.3,
                visual_type="mascot_ai",
                visual_goal="Miko neatly connects an oil drop to a dollar coin with a flexible dotted line, then points to a caveat badge.",
                mascot_action="drawing a flexible dotted line from oil to dollar and pointing to a caveat badge",
                setting="warm closing tabletop scene",
                media_query="oil dollar indirect relationship caveat mascot",
                voiceover_line="Connected, but indirect. Oil is one pressure, not the whole story.",
                on_screen_caption="CONNECTED, INDIRECT",
                key_words=["connected", "indirect", "bigger"],
                required_visual_elements=["Miko", "oil drop", "dollar coin", "dotted line"],
                forbidden_visual_elements=["human presenter", "trading advice"],
                fact_claim="The oil-dollar relationship is indirect and context-dependent.",
                source_needed=True,
                emotion="confident",
            ),
        ],
    )


def _generic_plan(topic: str, niche: str, mascot: MascotProfile) -> MascotStoryPlan:
    return MascotStoryPlan(
        topic=topic,
        niche=niche or "science",
        title=topic.rstrip("?"),
        story_angle="Miko turns the question into a concrete miniature story.",
        audience="Curious viewers who want a useful short explainer.",
        core_question=topic,
        simple_answer="Start with a concrete example, follow the mechanism, then keep the caveat attached.",
        analogy="A complicated system is easier to understand when one small object carries the pressure through the scene.",
        caveat="This is a simplified educational explanation.",
        caption="Miko explains the question with a story, a simple analogy, a mechanism, an example, and a caveat.",
        hashtags=["explained", "learn", "education"],
        mascot_id=mascot.mascot_id,
        scenes=[
            MascotStoryScene(
                scene_number=index,
                role=role,
                duration_target=3.0,
                visual_type=visual_type,
                visual_goal=f"Miko explains {topic} through a concrete visual scene.",
                mascot_action="explaining with a tiny prop" if visual_type in {"mascot_ai", "mixed"} else "none",
                setting="clean miniature educational scene",
                media_query=topic,
                voiceover_line=line,
                on_screen_caption=caption,
                fact_claim=line,
                source_needed=False,
                emotion="curious",
            )
            for index, (role, visual_type, line, caption) in enumerate(
                [
                    ("hook", "mascot_ai", f"Here is the simple version of {topic.rstrip('?')}.", "START HERE"),
                    ("question", "mixed", "First, turn the big question into one small scene.", "THE QUESTION"),
                    ("analogy", "object_scene_ai", "A simple analogy makes the pressure visible.", "THE ANALOGY"),
                    ("mechanism", "chart_motion", "Then follow the chain from cause to response.", "THE LINK"),
                    ("example", "broll_photo", "A real-world example makes it easier to remember.", "REAL WORLD"),
                    ("twist", "mixed", "The caveat keeps the answer honest.", "THE TRAP"),
                    ("takeaway", "mascot_ai", "The best answer is simple, but not oversimplified.", "THE TAKEAWAY"),
                ],
                start=1,
            )
        ],
    )
